### ISSUE TITLE
Звернення до міського голови - м.Гола Пристань - Херсонська область

### ISSUE THREAD

**Issue by annastolbova** [e-government-ua/iBP#726]
Відповідальна особа (ПІБ, посада) - Дробоженко
Світлана Миколаївна, начальник загального відділу

вул.1 Травня, 14
м.Гола Пристань
Херсонська область
75600

0553921555
vykonkom@golapristan-mrada.gov.ua

Координатор Проекту iGov в м. Херсоні та Херсонській області.
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel

**Comment by julyprodan** [comment]
@Kylikpavel 
https://test.igov.org.ua/service/659/general
логин/пароль golapristan_test

**Comment by Kylikpavel** [comment]
Можем запускать !!!

**Comment by julyprodan** [comment]
на боевом

**Comment by Kylikpavel** [comment]
А для бойового який логін/пароль для бойового, напишіть будь ласка )))  ???  

https://test.igov.org.ua/service/659/general 
логин/пароль golapristan_test 

25 травня 2016, 11:23:27, від "julyprodan" < notifications@github.com >: 

на боевом — 
You are receiving this because you were mentioned. 
Reply to this email directly or view it on GitHub 

-- 
----------------------------------------- 
Кулик Павло 

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net 
Тел: +380661622002 
Блог:https://www.facebook.com/kylikpavel, 
https://www.facebook.com/profile.php?id=10001084

**Comment by Kylikpavel** [comment]
Пишу снова, потому что так и не получил   логін/пароль ((( ((( ((( 

25 травня 2016, 15:21:06, від "Кулик Павло Миколайович" :

> А для бойового який логін/пароль для бойового, напишіть будь ласка )))  ???  
> 
> https://test.igov.org.ua/service/659/general 
> логин/пароль golapristan_test 
> 
> 25 травня 2016, 11:23:27, від "julyprodan" < notifications@github.com >: 
> 
> на боевом — 
> You are receiving this because you were mentioned. 
> Reply to this email directly or view it on GitHub 
> 
> -- 
> ----------------------------------------- 
> Кулик Павло 
> 
> Координатор Проекту iGov в м. Херсоні та Херсонській області. 
> Email: kylikpavel@ukr.net 
> Тел: +380661622002 
> Блог:https://www.facebook.com/kylikpavel, 
> https://www.facebook.com/profile.php?id=10001084 



-- 
-----------------------------------------
Кулик Павло

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net
Тел: +380661622002
Блог:https://www.facebook.com/kylikpavel, 
https://www.facebook.com/profile.php?id=10001084

**Comment by Kylikpavel** [comment]
Доброго дня - поміняйте будь ласка прізвище, не Дробженко, а Дробоженко. 
Буду дуде вдячний ))) 

25 травня 2016, 11:23:27, від "julyprodan" < notifications@github.com >: 

на боевом — 
You are receiving this because you were mentioned. 
Reply to this email directly or view it on GitHub 

-- 
----- 
Кулик Павло 

Координатор Проекту iGov в м. Херсоні та Херсонській області. 
Email: kylikpavel@ukr.net 
Тел: +380661622002 

ПОРТАЛ ДЕРЖАВНИХ ПОСЛУГ ХЕРСОН 
Блог:https://www.facebook.com/kylikpavel, 
https://ok.ru/profile/568464993102

**Comment by julyprodan** [comment]
заменила, спасибо
